/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package log4jexample;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;


public class App {

    static Logger log = LogManager.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        log.info("Begin logging !!!!");
        
        log.warn("Test Warning");
        
        log.log(Level.getLevel("DB"), "Testing dabase log only !");

        System.out.println(new App().getGreeting());

        log.info("Finish logging !!!!");
    }
}
